"use strict";
let places = ['makkah', 'madina', 'russia', 'usa', 'thailand'];
console.log('Original ' + places);
console.log('Copy ' + [...places].sort());
console.log('Original ' + places);
console.log('Copy ' + [...places].sort().reverse());
console.log('Original ' + places);
console.log('Original ' + places.reverse());
console.log('Original ' + places.reverse());
console.log('Original ' + places.sort());
console.log('Original ' + places.sort().reverse());
